### PR TITLE
Added option to remove/reinstall bloatware, and other tweaks

### PR DESCRIPTION
**Pull request by technocapeman**
I have added an additional option to remove or reinstall bloatware. This is not part of the essential tweaks, but rather it is a separate button. I also added more functionality such as removing bing from the start menu search, disabling Wi-Fi sense, and much more (check diff for full details).

Credits to [Craft Computing's Debloat Script](https://drive.google.com/file/d/1p5kzaeLoBzUDKqH1p4cgvi2sNShFHU5i/edit) for the list of bloatware and many other features.

### CODE REVIEW

**Comment by technocapeman** [comment]
You might also see PR #146 in the closed commits, I had an issue with git and I accidentally ended up closing that PR, and I wasn't able to reopen it either for some reason. This PR is the same thing as the old one. Sorry for the confusion!

**Review by ndroftheline — CHANGES_REQUESTED** [review]
i think there's a missing close curly bracket at line 913. powershell ise throws error.

**Comment by technocapeman** [comment]
> i think there's a missing close curly bracket at line 913. powershell ise throws error.

Thank you for letting me know! I just fixed the bug in [commit 7160952](https://github.com/ChrisTitusTech/win10script/pull/149/commits/71609526b132f5cd7e3b9167779af60051a80912).

**Comment by ndroftheline** [comment]
thanks so much for this addition - i think the bloatware capability is really valuable. 

unfortunately your script changes appear to break sysprep. it works with the original script (no bloatware apps removal) and breaks on these types of errors after your script is applied: 

`
2021-07-18 19:06:37, Info                  SYSPRP Entering SysprepGeneralizeValidate (Appx) - validating whether all apps are also provisioned.
2021-07-18 19:06:37, Error                 SYSPRP Package Microsoft.MicrosoftStickyNotes_3.6.73.0_x64__8wekyb3d8bbwe was installed for a user, but not provisioned for all users. This package will not function properly in the sysprep image.
2021-07-18 19:06:37, Error                 SYSPRP Failed to remove apps for the current user: 0x80073cf2.
2021-07-18 19:06:37, Error                 SYSPRP Exit code of RemoveAllApps thread was 0x3cf2.
2021-07-18 19:06:37, Error                 SYSPRP ActionPlatform::LaunchModule: Failure occurred while executing 'SysprepGeneralizeValidate' from C:\Windows\System32\AppxSysprep.dll; dwRet = 0x3cf2
2021-07-18 19:06:37, Error                 SYSPRP SysprepSession::Validate: Error in validating actions from C:\Windows\System32\Sysprep\ActionFiles\Generalize.xml; dwRet = 0x3cf2
2021-07-18 19:06:37, Error                 SYSPRP RunPlatformActions:Failed while validating Sysprep session actions; dwRet = 0x3cf2
2021-07-18 19:06:37, Error      [0x0f0070] SYSPRP RunDlls:An error occurred while running registry sysprep DLLs, halting sysprep execution. dwRet = 0x3cf2
2021-07-18 19:06:37, Error      [0x0f00d8] SYSPRP WinMain:Hit failure while pre-validate sysprep generalize internal providers; hr = 0x80073cf2`

**Comment by ndroftheline** [comment]
oddly, if i just run the debloat code manually, sysprep works.

in the debloat code i've found import-module references that appear to point to non-existant scripts; should these exist somewhere? starting at line 988:

    Import-Module -DisableNameChecking $PSScriptRoot\..\lib\take-own.psm1
    Import-Module -DisableNameChecking $PSScriptRoot\..\lib\New-FolderForced.psm1

then the new-folderforced command is called later at line 1132, which can't run.

    New-FolderForced -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent"

**Comment by ndroftheline** [comment]
no! it's not running it manually. 

it's running it *twice* 

seems the first run doesn't get to the step of running remove-appxprovisionedpackage cmdlets for some reason, at least on my system. can you reproduce? 

this probably needs to be fixed before it'll be merged since it breaks sysprep.

**Comment by technocapeman** [comment]
> no! it's not running it manually.
> 
> it's running it _twice_
> 
> seems the first run doesn't get to the step of running remove-appxprovisionedpackage cmdlets for some reason, at least on my system. can you reproduce?
> 
> this probably needs to be fixed before it'll be merged since it breaks sysprep.

As far as I see, I don't think the option of uninstalling bloatware breaks Sysprep. However, I did find out that disabling dmwappushservice does break sysprep. Maybe that's the reason why?

**Comment by ndroftheline** [comment]
i've found this pretty reproducible:

   1. follow craft computing's guide up until he runs his script
   (basically, create a basic unattend.xml, install windows 10 in a VM, enable
   builtin administrator user, login as administrator user and delete other
   user(s)
   2. run all updates on windows vm and reboot, take a snapshot
   3. open this modified script and hit remove bloatware button
   4. attempt sysprep; it fails with message reported earlier.
   5. re-open this modified script and hit remove bloatware button again
   6. attempt syspep; succeeds

afaict dwmappushservice isn't disabled, and the errors don't seem to be
related anyway. is it disabled as part of this remove bloatware script?

**Comment by technocapeman** [comment]
I removed some code that prevented bloat apps from returning, but I think it won't be of use because its best to run this script every 6 months anyway. See if Sysprep works now?

**Comment by technocapeman** [comment]
I can't seem to find a way to fix this problem, so I added a notice that this option will break sysprep. I did find out that Remove-AppxPackage can break sysprep, more details [here](https://virtuallyinclined.com/2017/01/08/windows-10-appx-packages-can-break-sysprep/).

Hopefully, we can merge this commit so that users can have the option to debloat their system.

**Comment by technocapeman** [comment]
This PR is ready for merging @ChrisTitusTech

**Comment by ChrisTitusTech** [comment]
Looks great all! Merging this

**Pull request merged**
