### PR TITLE
Add software and minor changes in win10debloat

### PR DESCRIPTION
**Pull request by GreenAndBlueG**
Changelog:
+ Added [XnView Classic](https://www.xnview.com/en/xnview/) and [MP](https://www.xnview.com/en/xnviewmp/) (2 image viewers)
+ Changed [MPC-HC](https://github.com/clsid2/mpc-hc) to [K-Lite Codec Pack](https://codecguide.com/about_kl.htm)
+ Minor Changes (Line [1050](https://github.com/GreenAndBlueG/win10script/commit/996f863fe18a639c6b85a486d194fea4aa69d54a#diff-e3f9015f2777fc802d116d3376f775782dc763db345aff75f26a51f2f54501eaR1050) and from [47](https://github.com/GreenAndBlueG/win10script/commit/996f863fe18a639c6b85a486d194fea4aa69d54a#diff-e3f9015f2777fc802d116d3376f775782dc763db345aff75f26a51f2f54501eaR1050) to [61](https://github.com/GreenAndBlueG/win10script/commit/996f863fe18a639c6b85a486d194fea4aa69d54a#diff-e3f9015f2777fc802d116d3376f775782dc763db345aff75f26a51f2f54501eaR1050))

### CODE REVIEW

**Comment by PrincessAkira** [comment]
K-Lite is from what i see the same MPC-HC on Git which is the latest one from where they take theyre Updates.

**Comment by GreenAndBlueG** [comment]
No, k-lite is a pack that include mpc-hc from [clsid2's git](https://github.com/clsid2/mpc-hc) plus other codecs. mpc-hc can play a lot of codecs out of the box but other software might need specific codecs for specific "platforms" (i.e DirectShow). A lot of software only tell you *"error playing this"* without saying *"hey i use DirectShow so maybe the problem is there"* so troubleshooting can be a lot difficult and installing a codec pack (such as k-lite) is the best option to solve it or prevent it (it least in my opinion)

**Comment by PrincessAkira** [comment]
> No, k-lite is a pack that include mpc-hc from [clsid2's git](https://github.com/clsid2/mpc-hc) plus other codecs. mpc-hc can play a lot of codecs out of the box but other software might need specific codecs for specific "platforms" (i.e DirectShow). A lot of software only tell you _"error playing this"_ without saying _"hey i use DirectShow so maybe the problem is there"_ so troubleshooting can be a lot difficult and installing a codec pack (such as k-lite) is the best option to solve it or prevent it (it least in my opinion)

I though his Repo was the official one. hmm.
Well then i would add FFDShow in there

**Comment by GreenAndBlueG** [comment]
Fddshow in included as optional in the gui installer of the mega pack (the one that i included in the script) but i don't think is possibile to chose that with winget

**Comment by PrincessAkira** [comment]
Well we can download it via ZIP.
I wrote something to do this on my PR, but if its included its fine lul

**Comment by ChrisTitusTech** [comment]
Can't use with current setup

**Pull request closed without merging**
