### PR TITLE
Disable Web Search

### PR DESCRIPTION
**Pull request by nikilson**
I found this option is very useful. added a registry key to the script which can block the internet and location access for the windows search. Now the search option only works for local machine and don't shows the web result....

### CODE REVIEW

**Comment by nikilson** [comment]
Unfortunately that key is not working in windows 11. I think they have changed the working of windows search. I tried this on my main production machine (Windows 10) this works perfectly as I expected. Titus if you don't want to merge, add it manually or reject this pull request. BTW this is my first Open Source contribution. ;-)

**Comment by ChrisTitusTech** [comment]
I'm integrating this directly into essential tweaks.

**Comment by DocAElstein** [comment]
HI
I have just started here and am struggling a bit to figure the place out still, so I apologies if as a result of my ignorance I am talking rubbish here.
I have my own fuller rough notes here, which  explain better in detail what I am trying to say , 
https://excelfox.com/forum/showthread.php/2408-Windows-10-and-Office-Excel/page50#post12767
, but I will just give the TLDR version here

Chris tested/ looked at this Disable Web Search addition as part of a Live Stream.  
I could be mistaken, but I think he messed it up: He made the change on a script, but I think then some time later in the same Live Stream video tested the wrong script that did not have the change in it, and so he came to the conclusion ( wrong possibly conclusion *** ) . He concluded that in the most recent windows 10 version it does not work.
Furthermore, if I understood correctly , he said he had made the addition anyway as he suspected it would work on earlier windows 10 versions.
Two things:
_1 In the meantime I have tested this addition on several windows 10 computers with different versions, including the most recent windows 10 version ***, and so far it always works ( It does not work on my one windows 11 computer, which ties up with what nikilson has said already)
_ 2 I have been looking at this script   (- the one you come to on google search like windows 10 debloat scripts GitHub Chris Titus Tech),  on and off in the last few weeks, and I don’t think the change has ever been added.

Regarding _2 , possibly this is just showing my ignorance, and the change is in some twig of a branched forkedid spooned version waiting in the wings somewhere that I don’t know about yet, Lol :)

Alan

**Comment by nikilson** [comment]
Just now I watched the live stream. Disable Web Search works perfectly for me over 5 months. This will not work on Windows 11, Microsoft has changed how Search works on windows 11. My main laptop is up to date running 20H2. For reference
disable_websearch . 

For Windows 11 we need to do some research. This will technique will completely replace apps like Wox, power toys - search.
I know you are too busy. If you are interested in this pull request, reply to me I will make another pull request similar to what you did on that video. You clone my repo try another time if that doesn't work just ditch this idea.

**Comment by DocAElstein** [comment]
@nikilson
Hi there Renardo
( I am Alan Elston – I don’t have any connections to Chris Titus. I have been following his work, but I am not one of his “team” or anything like that)

I am very new to GitHub, I don’t yet understand it fully. (I only joined yesterday)
(I am not a computer profi either. I have just been following Chris ‘s stuff for the last couple  of years to help me debloat some computers in my family and a for few friends computers)

I wasn’t sure if anybody ever reads any of these old comments. I  thought there was a small chance that you might get a notification if I posted. I thought you might be interested, just in parsing, in my thinking, after I had seen that Live Stream Video. That’s all. Just passing interest to you, nothing else.

I know that Chris hates Reply and Email notifications, so he turns them all off. So I don’t think Chris will ever come here and read anything that we are writing here. I think it’s unlikely that anybody other than you and me will ever again read anything  here in this old Pull request of yours.

My best guess is that Chris may  have  mistakenly thought that he put your addition into his script. (I just took another look at his most current script. Your addition is still not there.)
 I expect he has long since forgotten all about it. But I may be wrong, because I don’t understand how GitHub works yet. 


I recently decided that it would be quicker to write my own script. It will all be very much thanks to Chris because I have learnt so much from him in the last few years. 
But I think that it will be much quicker for me to write my own script, rather than, making suggestions to Chris anywhere, which he rarely has time to read. If he does read them, then quite often he messes it up, as I think he did in your case.


I am making my own rough notes on my progress here:
https://excelfox.com/forum/showthread.php/2408-Windows-10-and-Office-Excel/page52
https://excelfox.com/forum/showthread.php/2408-Windows-10-and-Office-Excel/page51
https://excelfox.com/forum/showthread.php/2408-Windows-10-and-Office-Excel/page50
Those notes are purely for my own personal use. But you are very welcome to view them at any time.

I will be including your Disable Web Search addition suggestion in my own personal script.

Alan

**Pull request closed without merging**
