### PR TITLE
Added waterfox install

### PR DESCRIPTION
**Pull request by Sparker-99**
I agree it is a good browser without Firefox's telemetry. Requests #195 & #268

### CODE REVIEW

**Review by micziz — APPROVED** [review]
LGTM! Think it's a good idea

**Comment by d4rklynk** [comment]
Waterox has been bought by system1, and updates are really slow. Waterfox is just another Firefox, but worst. It is just my point of view though. I opened an issue to add Librewolf, that is way better than Waterfox.

**Comment by micziz** [comment]
> Waterox has been bought by system1, and updates are really slow. 

So, it isn't the only software that releases updates slowly

> I opened an issue to add Librewolf, that is way better than Waterfox

I think Waterfox is better since it's based on firefox, and has a similar ui to it.

> What I'm saying is just I think the script is more to debloat Windows and add some tools (at least) FOSS and/or useful. And the script is here to gain a little more privacy. So Waterfox for me is the opposite of that.

Waterfox isn't bloated, in fact, against other browsers in the script (brave...) are more bloated than waterfox. Also water fox is soooooo private. It actually asks you if you want to switch to Startpage for default. (also, just a reminder, system1, owns not only Waterfox, but also start page, so don't think there google.)

> Waterfox doesn't have good balance between privacy/convenience/security.

I think you are wrong. 
Privacy: Does not receive payments from google, and is owned by the same company witch owns StartPage!!! Also 
> (it just Firefox without Mozilla Telemetry)

Convinience: 
> (it just Firefox without Mozilla Telemetry)

You said it, if you know Firefox, you are at home with Waterfox.

Security:
I use water fox on a daily basis, saving passwords, among other things. Never ever been afraid.

> You gain little to lose a lot.

Not really... You are just gaining a secure and private Browser without having to worry about Mozilla

> I just prefer to see Librewolf on the script than Waterfox

You know we can put both.

**Comment by d4rklynk** [comment]
> > I opened an issue to add Librewolf, that is way better than Waterfox
> 
> I think Waterfox is better since it's based on Firefox, and has a similar ui to it.
Librewolf is exactly the same. Based on last Firefox. Same UI. Actual version is 98.0.1 and we have updates in the day (or 3 days after).
> 
> > What I'm saying is just I think the script is more to debloat Windows and add some tools (at least) FOSS and/or useful. And the script is here to gain a little more privacy. So Waterfox for me is the opposite of that.
> 
> Waterfox isn't bloated, in fact, against other browsers in the script (brave...) are more bloated than waterfox. Also water fox is soooooo private. It actually asks you if you want to switch to Startpage for default. (also, just a reminder, system1, owns not only Waterfox, but also start page, so don't think there google.)
I explained wrong. I don't think WF is bloated (but yeah Brave is...) but WF is little tweaked compared to LW, and I didn't think you could bother to put WF on the script (in my opinion). But yeah as you said, we can put both, and it would be great tbh.
> > Waterfox doesn't have good balance between privacy/convenience/security.
> 
> I think you are wrong. Privacy: Does not receive payments from google, and is owned by the same company witch owns StartPage!!! Also
When I said that, I meant that telemetry is disabled by default and you have slow updates. With Librewolf, you have a lot good features enabled by default and "bad" features disabled by default and slow updates (well, in the day or 3 days late max). For LW there's a lot of good tweaks compared to WF.
And they don't want to receive payments at all btw.
> > You gain little to lose a lot.
> 
> Not really... You are just gaining a secure and private Browser without having to worry about Mozilla
For me, Waterfox is just some tweaks, that you can already do in the settings of FF. And Librewolf enables all RFP, ETP, and privacy features, disables Google Safe Browsing and Mozilla related (I don't say it is for everyone though).
> You know we can put both.
You're completely right, it would be really awesome tbh.

**Comment by d4rklynk** [comment]
And btw, if you want add button for another soft. You need to shift every others button (from what I understand from the script)

**Comment by micziz** [comment]
> Btw, if you want to add button for another soft. You need to shift every others button (from what I understand from the script)

Yhea, this is up to @ChrisTitusTech or guys like that since that is waaaay more fundamental

**Comment by micziz** [comment]
Also @d4rklynk If you want open a PR to add LibreWolf... You said you just put and issue?

**Comment by d4rklynk** [comment]
> Also @d4rklynk If you want open a PR to add LibreWolf... You said you just put and issue?

Yeah I just put an issue, I can add a PR maybe. Or we can edit this one to ask for WF and LW ?

**Comment by ChrisTitusTech** [comment]
Not a fan of waterfox

**Pull request closed without merging**
