### PR TITLE
Install Brave and OOSU10 with Chocolatey

### LINKED ISSUE #57: Why not install Brave and OOShutUp10 with Chocolatey?

### PR DESCRIPTION
**Pull request by DestroyerXyz**
Fixes #57

### CODE REVIEW

**Comment by TassiloBalbo** [comment]
OOSU10 isn't open source, wouldn't trust it to make changes to my OS

**Comment by DestroyerXyz** [comment]
@TassiloBalbo It is already in the code and is optional to install. I just changed the installation source

**Comment by ChrisTitusTech** [comment]
Thanks all merged the changes.

**Comment by natri23** [comment]
Wouldn't you need to download oooshutup10.cfg first for this to work?
This change will make the one command below stop working:

`iex ((New-Object System.Net.WebClient).DownloadString('https://git.io/JJ8R4'))
`

**Comment by DestroyerXyz** [comment]
The cfg is downloaded when you clone the whole repo with that command

**Comment by natri23** [comment]
> The cfg is downloaded when you clone the whole repo with that command

That command only run the win10debloat.ps script. It does not download anything else unless instructed within the script.

**Pull request merged**
